### ISSUE TITLE
cassandra-cpp-driver - 2.9.0-yb-9 - compilation problem on debian:buster

### ISSUE THREAD

**Issue by vtzan** [YugaByte/cassandra-cpp-driver#6] opened 2020-10-23 16:55 UTC
Dear Team,

I have faced compilation problems on debian:buster using the latest cassandra-cpp-driver 2.9.0-yb-9

I tried with 2.9.0-yb-8 and it compiled fine.
BTW In 2.9.0-yb-8 version I had also to remove the -Werror flag twice from ./cmake/modules/CppDriver.cmake to ignore warnings and to proceed with the compilation

I have attached the full log here --> https://pastebin.com/ufhzrsqn

Best Regards
Vasilios Tzanoudakis

**Comment by tedyu** [comment] 2020-10-23 17:49
Please sync with repo and retry.

**Comment by vtzan** [comment] 2020-10-26 17:37
Dear Team,

Problem still exists.


```
Step 16/40 : RUN git clone https://github.com/yugabyte/cassandra-cpp-driver.git && cd cassandra-cpp-driver && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && make install
--
877 | ---> Running in 0c71dd362ed1
878 | Cloning into 'cassandra-cpp-driver'...
879 | -- The C compiler identification is GNU 8.3.0
880 | -- The CXX compiler identification is GNU 8.3.0
881 | -- Check for working C compiler: /usr/bin/cc
882 | -- Check for working C compiler: /usr/bin/cc -- works
883 | -- Detecting C compiler ABI info
884 | -- Detecting C compiler ABI info - done
885 | -- Detecting C compile features
886 | -- Detecting C compile features - done
887 | -- Check for working CXX compiler: /usr/bin/c++
888 | -- Check for working CXX compiler: /usr/bin/c++ -- works
889 | -- Detecting CXX compiler ABI info
890 | -- Detecting CXX compiler ABI info - done
891 | -- Detecting CXX compile features
892 | -- Detecting CXX compile features - done
893 | CMake Deprecation Warning at cmake/modules/CppDriver.cmake:289 (cmake_policy):
894 | The OLD behavior for policy CMP0042 will be removed from a future version
895 | of CMake.
896 |  
897 | The cmake-policies(7) manual explains that the OLD behaviors of all
898 | policies are deprecated and that a policy should be set to OLD only under
899 | specific short-term circumstances.  Projects should be ported to the NEW
900 | behavior and not rely on setting a policy to OLD.
901 | Call Stack (most recent call first):
902 | CMakeLists.txt:13 (CassPolicies)
903 |  
904 |  
905 | CMake Deprecation Warning at cmake/modules/CppDriver.cmake:294 (cmake_policy):
906 | The OLD behavior for policy CMP0048 will be removed from a future version
907 | of CMake.
908 |  
909 | The cmake-policies(7) manual explains that the OLD behaviors of all
910 | policies are deprecated and that a policy should be set to OLD only under
911 | specific short-term circumstances.  Projects should be ported to the NEW
912 | behavior and not rely on setting a policy to OLD.
913 | Call Stack (most recent call first):
914 | CMakeLists.txt:13 (CassPolicies)
915 |  
916 |  
917 | -- PROJECT version: 2.9.0
918 | -- Found Libuv: /usr/lib/libuv.so
919 | -- LIBUV version: 1.40.0
920 | -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so (found version "1.1.1d")
921 | CMake Deprecation Warning at cmake/modules/CppDriver.cmake:690 (cmake_policy):
922 | The OLD behavior for policy CMP0054 will be removed from a future version
923 | of CMake.
924 |  
925 | The cmake-policies(7) manual explains that the OLD behaviors of all
926 | policies are deprecated and that a policy should be set to OLD only under
927 | specific short-term circumstances.  Projects should be ported to the NEW
928 | behavior and not rely on setting a policy to OLD.
929 | Call Stack (most recent call first):
930 | CMakeLists.txt:127 (CassSetCompilerFlags)
931 |  
932 |  
933 | -- Using std::atomic implementation for atomic operations
934 | -- Checking to see if CXX compiler accepts flag -std=c++11
935 | -- Checking to see if CXX compiler accepts flag -std=c++11 - yes
936 | -- Using hash header <functional> and namespace "std"
937 | -- Looking for inttypes.h
938 | -- Looking for inttypes.h - found
939 | -- Looking for stdint.h
940 | -- Looking for stdint.h - found
941 | -- Looking for sys/types.h
942 | -- Looking for sys/types.h - found
943 | -- Looking for memcpy
944 | -- Looking for memcpy - found
945 | -- Looking for stddef.h
946 | -- Looking for stddef.h - found
947 | -- Check size of long long
948 | -- Check size of long long - done
949 | -- Check size of uint16_t
950 | -- Check size of uint16_t - done
951 | -- Check size of u_int16_t
952 | -- Check size of u_int16_t - done
953 | -- Check size of __uint16_t
954 | -- Check size of __uint16_t - done
955 | -- Looking for GRND_NONBLOCK
956 | -- Looking for GRND_NONBLOCK - found
957 | -- Looking for SO_NOSIGPIPE
958 | -- Looking for SO_NOSIGPIPE - not found
959 | -- Looking for sigtimedwait
960 | -- Looking for sigtimedwait - found
961 | -- Performing Test HAVE_BUILTIN_BSWAP32
962 | -- Performing Test HAVE_BUILTIN_BSWAP32 - Success
963 | -- Performing Test HAVE_BUILTIN_BSWAP64
964 | -- Performing Test HAVE_BUILTIN_BSWAP64 - Success
965 | -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
966 | -- Configuring done
967 | -- Generating done
968 | -- Build files have been written to: /tmp/cassandra-cpp-driver/build
969 | Scanning dependencies of target cassandra
970 | [  1%] Building CXX object CMakeFiles/cassandra.dir/src/abstract_data.cpp.o
971 | [  2%] Building CXX object CMakeFiles/cassandra.dir/src/address.cpp.o
972 | [  3%] Building CXX object CMakeFiles/cassandra.dir/src/auth.cpp.o
973 | [  5%] Building CXX object CMakeFiles/cassandra.dir/src/auth_requests.cpp.o
974 | [  6%] Building CXX object CMakeFiles/cassandra.dir/src/auth_responses.cpp.o
975 | [  7%] Building CXX object CMakeFiles/cassandra.dir/src/batch_request.cpp.o
976 | In file included from /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/densehashtable.h:101,
977 | from /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/dense_hash_set:108,
978 | from /tmp/cassandra-cpp-driver/src/address.hpp:22,
979 | from /tmp/cassandra-cpp-driver/src/serialization.hpp:20,
980 | from /tmp/cassandra-cpp-driver/src/buffer.hpp:21,
981 | from /tmp/cassandra-cpp-driver/src/request.hpp:20,
982 | from /tmp/cassandra-cpp-driver/src/batch_request.hpp:23,
983 | from /tmp/cassandra-cpp-driver/src/batch_request.cpp:17:
984 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/libc_allocator_with_realloc.h: In instantiation of 'T* sparsehash::libc_allocator_with_realloc<T>::reallocate(sparsehash::libc_allocator_with_realloc<T>::pointer, sparsehash::libc_allocator_with_realloc<T>::size_type) [with T = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; sparsehash::libc_allocator_with_realloc<T>::pointer = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >*; sparsehash::libc_allocator_with_realloc<T>::size_type = long unsigned int]':
985 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/densehashtable.h:1202:15:   required from 'sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::alloc_impl<sparsehash::libc_allocator_with_realloc<U> >::pointer sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::alloc_impl<sparsehash::libc_allocator_with_realloc<U> >::realloc_or_die(sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::alloc_impl<sparsehash::libc_allocator_with_realloc<U> >::pointer, sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::alloc_impl<sparsehash::libc_allocator_with_realloc<U> >::size_type) [with A = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; Value = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; Key = std::__cxx11::basic_string<char>; HashFcn = std::hash<std::__cxx11::basic_string<char> >; ExtractKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SelectKey; SetKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SetKey; EqualKey = std::equal_to<std::__cxx11::basic_string<char> >; Alloc = sparsehash::libc_allocator_with_realloc<std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> > >; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::alloc_impl<sparsehash::libc_allocator_with_realloc<U> >::pointer = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >*; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::alloc_impl<sparsehash::libc_allocator_with_realloc<U> >::size_type = long unsigned int]'
986 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/densehashtable.h:628:11:   required from 'void sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::resize_table(sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type, sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type, sparsehash::true_type) [with Value = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; Key = std::__cxx11::basic_string<char>; HashFcn = std::hash<std::__cxx11::basic_string<char> >; ExtractKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SelectKey; SetKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SetKey; EqualKey = std::equal_to<std::__cxx11::basic_string<char> >; Alloc = sparsehash::libc_allocator_with_realloc<std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> > >; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int; sparsehash::true_type = sparsehash::integral_constant<bool, true>]'
987 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/densehashtable.h:785:9:   required from 'void sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; Key = std::__cxx11::basic_string<char>; HashFcn = std::hash<std::__cxx11::basic_string<char> >; ExtractKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SelectKey; SetKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SetKey; EqualKey = std::equal_to<std::__cxx11::basic_string<char> >; Alloc = sparsehash::libc_allocator_with_realloc<std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> > >; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]'
988 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/densehashtable.h:638:5:   required from 'void sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::copy_from(const sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>&, sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; Key = std::__cxx11::basic_string<char>; HashFcn = std::hash<std::__cxx11::basic_string<char> >; ExtractKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SelectKey; SetKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SetKey; EqualKey = std::equal_to<std::__cxx11::basic_string<char> >; Alloc = sparsehash::libc_allocator_with_realloc<std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> > >; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]'
989 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/densehashtable.h:729:5:   required from 'sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::dense_hashtable(const sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>&, sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; Key = std::__cxx11::basic_string<char>; HashFcn = std::hash<std::__cxx11::basic_string<char> >; ExtractKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SelectKey; SetKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SetKey; EqualKey = std::equal_to<std::__cxx11::basic_string<char> >; Alloc = sparsehash::libc_allocator_with_realloc<std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> > >; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]'
990 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/densehashtable.h:620:21:   required from 'bool sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::resize_delta(sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; Key = std::__cxx11::basic_string<char>; HashFcn = std::hash<std::__cxx11::basic_string<char> >; ExtractKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SelectKey; SetKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SetKey; EqualKey = std::equal_to<std::__cxx11::basic_string<char> >; Alloc = sparsehash::libc_allocator_with_realloc<std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> > >; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]'
991 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/densehashtable.h:998:16:   required from 'sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::value_type& sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::find_or_insert(const key_type&) [with DefaultValue = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::DefaultValue; Value = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; Key = std::__cxx11::basic_string<char>; HashFcn = std::hash<std::__cxx11::basic_string<char> >; ExtractKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SelectKey; SetKey = sparsehash::dense_hash_map<std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >::SetKey; EqualKey = std::equal_to<std::__cxx11::basic_string<char> >; Alloc = sparsehash::libc_allocator_with_realloc<std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> > >; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::value_type = std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >; sparsehash::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::key_type = std::__cxx11::basic_string<char>]'
992 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/dense_hash_map:264:59:   required from 'sparsehash::dense_hash_map<Key, T, HashFcn, EqualKey, Alloc>::data_type& sparsehash::dense_hash_map<Key, T, HashFcn, EqualKey, Alloc>::operator[](const key_type&) [with Key = std::__cxx11::basic_string<char>; T = cass::SharedRefPtr<const cass::PreparedMetadata::Entry>; HashFcn = std::hash<std::__cxx11::basic_string<char> >; EqualKey = std::equal_to<std::__cxx11::basic_string<char> >; Alloc = sparsehash::libc_allocator_with_realloc<std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> > >; sparsehash::dense_hash_map<Key, T, HashFcn, EqualKey, Alloc>::data_type = cass::SharedRefPtr<const cass::PreparedMetadata::Entry>; sparsehash::dense_hash_map<Key, T, HashFcn, EqualKey, Alloc>::key_type = std::__cxx11::basic_string<char>]'
993 | /tmp/cassandra-cpp-driver/src/prepared.hpp:113:26:   required from here
994 | /tmp/cassandra-cpp-driver/src/third_party/sparsehash/src/sparsehash/internal/libc_allocator_with_realloc.h:68:40: error: 'void* realloc(void*, size_t)' moving an object of non-trivially copyable type 'struct std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >'; use 'new' and 'delete' instead [-Werror=class-memaccess]
995 | return static_cast<pointer>(realloc(p, n * sizeof(value_type)));
996 | ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
997 | In file included from /usr/include/c++/8/utility:70,
998 | from /usr/include/c++/8/algorithm:60,
999 | from /tmp/cassandra-cpp-driver/src/hash.hpp:20,
1000 | from /tmp/cassandra-cpp-driver/src/address.hpp:20,
1001 | from /tmp/cassandra-cpp-driver/src/serialization.hpp:20,
1002 | from /tmp/cassandra-cpp-driver/src/buffer.hpp:21,
1003 | from /tmp/cassandra-cpp-driver/src/request.hpp:20,
1004 | from /tmp/cassandra-cpp-driver/src/batch_request.hpp:23,
1005 | from /tmp/cassandra-cpp-driver/src/batch_request.cpp:17:
1006 | /usr/include/c++/8/bits/stl_pair.h:208:12: note: 'struct std::pair<const std::__cxx11::basic_string<char>, cass::SharedRefPtr<const cass::PreparedMetadata::Entry> >' declared here
1007 | struct pair
1008 | ^~~~
1009 | cc1plus: all warnings being treated as errors
1010 | make[2]: *** [CMakeFiles/cassandra.dir/build.make:128: CMakeFiles/cassandra.dir/src/batch_request.cpp.o] Error 1
1011 | make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/cassandra.dir/all] Error 2
1012 | make: *** [Makefile:152: all] Error 2
1013 | The command '/bin/sh -c git clone https://github.com/yugabyte/cassandra-cpp-driver.git && cd cassandra-cpp-driver && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && make install' returned a non-zero code: 2


```

thank you in advance
Vasilios Tzanoudakis

**Comment by tedyu** [comment] 2020-10-26 19:29
The code which caused the error was from upstream:
```
git log src/third_party/sparsehash/src/sparsehash/internal/libc_allocator_with_realloc.h
commit a3fd7d3c79f6b6d95e462ca74a22d78d62eb9c84
Author: Michael Penick <michael.penick@datastax.com>
Date:   Tue Mar 15 15:29:26 2016 -0700

    Vendored Sparsehash
```
There hasn't been any change since 2016 for sparsehash.

**Comment by OlegLoginov** [comment] 2020-10-27 18:22
@vtzan Please check that you took latest 2.9.0-yb-10 version. (2.9.0-yb-9 is brocken).
And currently we support only Linux:  Ubuntu & CentOS.

**Comment by tedyu** [comment] 2020-10-27 18:31
Oleg and I haven't been able to reproduce the above error with latest driver code.

**Comment by OlegLoginov** [comment] 2020-11-01 18:49
Closing the issue because it's not reproduced with v2.9.0-yb-10.

**Closed as completed by OlegLoginov** 2020-11-01 18:49 UTC
